from . import property_land
from . import property_land_type
from . import property_water_consumption
from . import property_land_type_water_consumption_rule
from . import property_water_consumption_computation_parameter
from . import property_water_consumption_computation_parameter_line
from . import property_water_consumption_issue
from . import property_water_consumption_route
from . import invoice
from . import wizard
from . import res_partner
