CREATE OR REPLACE VIEW public.vw_property_settings_monthly_last
AS SELECT psm.year_month,
    psm.invoice_date_due,
    psm.index_coin,
    psm.year_month_multa,
    psm.year_month_property_tax,
    psm.year_month_property_ga_tax,
    psm.year_month_property_water_consumption,
    psm.year_month_property_water_catchment,
    psm.nextread_date,
    psm.rate_catchment,
    psm.ar_period,
    psm.ar_ph,
    psm.ar_ph_limit,
    psm.ar_uh_color,
    psm.ar_uh_color_limit,
    psm.ar_ut_turbidity,
    psm.ar_ut_turbidity_limit,
    psm.ar_chlorine_residual,
    psm.ar_chlorine_residual_limit,
    psm.ar_fluorides,
    psm.ar_fluorides_limit,
    psm.ar_ecoli,
    psm.ar_ecoli_limit,
    psm.property_tax_fixed_value,
    psm.property_tax_minimal_contribution,
    psm.property_tax_monthly_index,
    psm.inpc
   FROM vw_property_settings_monthly psm
  ORDER BY psm.year_month DESC
 LIMIT 1;